// Generated by https://quicktype.io

export class CWiki {
    pages: CPage[];
}

export class CPage {
    id:            number;
    key:           string;
    title:         string;
    excerpt:       string;
    matched_title: null;
    description:   null;
    thumbnail:     CThumbnail;
}

export class CThumbnail {
    mimetype: string;
    size:     number;
    width:    number;
    height:   number;
    duration: null;
    url:      string;
}
